=== dmwmishere/universal/Main/src/main/resources/xsds/dataTypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/dataTypes" xmlns:tns="http://www.example.org/dataTypes" elementFormDefault="qualified">

    <element name="meme" type="tns:memedesc"></element>
    
    <complexType name="memedesc">
    	<sequence>
    		<element name="id" type="int" maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="datetime" type="dateTime" maxOccurs="1" minOccurs="0"></element>
    		<element name="uuid" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="name" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="dankLevel" type="int" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="crc32" type="long" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="fileType" type="tns:t_fileType" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="data" type="string" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="t_fileType">
    	<sequence>
    		<element name="extension"
    			type="tns:ExtensionType">
    		</element>
    	</sequence>
    	<attribute name="size" type="int" use="optional" default="10000"></attribute>
    </complexType>

    <complexType name="extensions"></complexType>

    <element name="memerq" type="tns:memedesc"></element>

    <element name="memers" type="tns:response"></element>
    
    <complexType name="response">
    	<sequence>
    		<element name="RqUID" type="string"></element>
    		<element name="RqTime" type="dateTime"></element>
    		<element name="MemeInfo" type="tns:MemeInfoType"></element>
    	</sequence>
    </complexType>

    <complexType name="MemeInfoType">
    	<sequence>
    		<element name="Year" maxOccurs="1" minOccurs="0">
    			<simpleType>
    				<restriction base="int">
    					<minExclusive value="1980"></minExclusive>
    					<maxExclusive value="2040"></maxExclusive>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="Type" maxOccurs="1" minOccurs="0"
    			type="tns:MemeType">
    		</element>
    		<element name="Origin" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="Status" maxOccurs="1" minOccurs="1">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="Confirmed"></enumeration>
    					<enumeration value="Submission"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="Badge" type="string" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <simpleType name="ExtensionType">
    	<restriction base="string">
    		<enumeration value="GZ"></enumeration>
    		<enumeration value="ZIP"></enumeration>
    		<enumeration value="PLAIN"></enumeration>
    		<enumeration value="RAR"></enumeration>
    		<enumeration value="PNG"></enumeration>
    		<enumeration value="JPEG"></enumeration>
    	</restriction>
    </simpleType>

    <simpleType name="MemeType">
    	<restriction base="string">
    		<enumeration value="Character"></enumeration>
    		<enumeration value="Shitposting"></enumeration>
    		<enumeration value="VideoGame Character"></enumeration>
    	</restriction>
    </simpleType>

    <simpleType name="MemeStatus">
    	<restriction base="string"></restriction>
    </simpleType>
</schema>

=== dmwmishere/universal/External/src/main/resources/xsds/snipars.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:meme xmlns:tns="http://www.example.org/dataTypes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/dataTypes dataTypes.xsd ">
  <tns:id>0</tns:id>
  <tns:datetime>2001-12-31T12:00:00</tns:datetime>
  <tns:uuid>123123123123</tns:uuid>
  <tns:name>xXx_Sn1pars_xXx</tns:name>
  <tns:dankLevel>1337</tns:dankLevel>
  <tns:fileType size="420">
  	<tns:extension>PLAIN</tns:extension>
  </tns:fileType>
  <tns:data>9/11 - would quick sc0pe</tns:data>
</tns:meme>
